### ISSUE TITLE
Arquitetura web

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#11]
Alterar a camada de apresentação para web:
- utilizar algum framework que permita Front Controller (Swing/Struts2/VRaptor).
- utilizar front-end responsivo (API do twitter?)

**Comment by calebepb** [comment]
A parte de front-end responsivo será quebrado em outra issue.

**Comment by calebepb** [comment]
Será usado VRaptor!

**Comment by jeanmx09** [comment]
Estrutura do Ambiente Web:

1) Front-End
- Wireframes (UX - User  Experience, UI - User Interface)
- HTML5
- CSS3
- Adobe Photoshop
- Framework Front-End: Bootstrap
- Mobile First

2) Integração entre camadas (Front-End/Back-End)
- Angular (Two way data binding, +performance)
- REST (Webservice)

3) Back-End
- Java

4) Testes
- Protractor

**Comment by jeanmx09** [comment]
Favor quebrar as etapas acima em Issues.

**Comment by calebepb** [comment]
Apenas por curiosidade: você mesmo pode quebrar as etapas acima em issues.
Aliás, quais são as etapas? Os números ou os bullets?

**Comment by jeanmx09** [comment]
Irei adicionar cada etapa em issues diferentes, seguem as etapas em ordem de execução:

1) Front-End:
- Desenho das possíveis telas seguindo os padrões de UX/UI com Mobile First.
- Codificação das telas desenhadas previamente já com uso do angular em sua estrutura HTML
- Ajustes visuais e responsivos com CSS e Bootstrap.

2) Integração entre as camadas:
- Com a estrutura HTML (com Angular) já pronta, desenvolver os métodos para consumir os webservices no back-end Java.
- Desenvolver os métodos de comunicação de retorno do back-end Java para o front JS.
- Webservices (REST)

3) Testes
- Desenvolvimento das funções para o Protractor, afim de automatizar os testes.
