### ISSUE TITLE
Arquivos jacoco?

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#13]
O que esses arquivos jacoco? Me parecem testes, mas, como funcionam?
Criar página na Wiki explicando isso também!

**Comment by calebepb** [comment]
Algumas coisas em http://eclemma.org/jacoco/

**Comment by calebepb** [comment]
Ele pode ser integrado com o Codacy, que já está "ligado" a este repositório. Falta configurar, veja issue correspondente.

**Comment by jonatasmaxi** [comment]
Os arquivos Jacoco pertencem a Java Code Coverage Library e são responsáveis por fazer a análise da cobertura de código em linguagem Java usando um conjunto variado de métricas. Calcula diversos tipos de cobertura de código: por instruções, por branch,  por complexidade ciclomática, por método, por classe e por linha. São integráveis a diversas ferramentas de build e deployment, independente do ambiente de execução. 

Link para documentação: http://eclemma.org/jacoco/trunk/doc/index.html

**Comment by calebepb** [comment]
Gostei desse resumo... me lembrou algumas aulas de laboratório, não é mesmo?!?!? ;)

**Comment by calebepb** [comment]
Remover esses arquivos do repositório, pois eles devem ser gerados pelo build e enviados para o codacy.
Portanto, configurar o build para gerar os relatórios do projeto e enviar para o codacy. Com certeza isso tem a ver com a issue #17. Se aquela issue não habilitar o jacoco, esta issue deve fazer isso.

**Comment by jonatasmaxi** [comment]
OK, o arquivo javacoverage.report.xml  é o responsável por indicar a configuração desses arquivos no repositório, certo? Pois para setup do coverage no codacy ele assume que a cobertura do código esteja configurada no repositório e na hora da execução da última parte do script, um dos parâmetros do comando é o arquivo de report.

**Comment by jonatasmaxi** [comment]
Arquivos removidos na branch issue-17' deseja que crie uma nova branch somente para remoção dos arquivos e fechamento dessa issue?

**Comment by calebepb** [comment]
Remoção realmente feita na issue #17, commit 128f6b1
