### ISSUE TITLE
Melhorar a qualidade de src/datamapper/AusenciaJpaController.java

### ISSUE THREAD

**Issue by YsabelleSousa** [Prof-Calebe/substituicao#137]
Observar o relatório do Codacy (branch dev) para melhorar a qualidade deste código.

**Comment by LeoFuso** [comment]
Seguindo as instruções do Codacy, realizei já algumas alterações:

Separei o package do comentário acima,
Adicionei referências a classe "this" nos métodos de classe.
Removi Exceptions genéricas, adicionando algumas mais específicas.
Modifiquei também algumas mensagens da exception por mensagens mais específicas,
adicionei uma cláusula de Exception para o método findAusencia(Long id),
dentre outras coisas menores.

Commit parcial, apenas para testar os Hooks.

Coisa que aparentemente não deu muito certo, pois o Travis reprovou completamente o meu commit - e eu não faço ideia do porque, se puder me dar uma luz, professor, agradecerei. 
E eu esperava um feedback do Codacy, mas eu não consegui encontra-lo.

**Comment by calebepb** [comment]
Fala Leonardo!
Então, minha sugestão pra você é que os commits sejam de mudanças pequenas e parciais dos códigos. Tem muita coisa que você fez em 1 único commit - isso dificulta voltar atrás com alguma correção, se for necessário.
A outra coisa: é fundamental compilar o projeto em seu computador. O erro apontado no Travis é de compilação - uma Exception não está sendo tratada. Veja isso com carinho.
Por último, o Codacy só apontará relatórios quando você fizer um pull request no Github.

**Comment by LeoFuso** [comment]
Certo! Anotado. 
Obrigado, professor.
