### ISSUE TITLE
Estrutura do repositório comprometida

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#14]
A estrutura do projeto está no formato Netbeans. Ela deve ser refeita para ficar independente de IDE.

**Comment by calebepb** [comment]
Minha sugestão, apenas:

- src
- test
- lib

Cada desenvolvedor deverá configurar sua infraestrutura para compilar/executar/testar a aplicação.

**Comment by calebepb** [comment]
Claro que arquivos como _build.sh_, _travis.yml_  _README.MD_ e _.gitignore_ **devem** ser mantidos na raiz do projeto.

**Comment by jonatasmaxi** [comment]
Será refeita a estrutura do projeto mas o sistema de build ainda será totalmente dependente do netbeans

**Comment by calebepb** [comment]
Adicionar `/doc`, conforme issue #5 .

**Comment by jonatasmaxi** [comment]
Estrutura do projeto refeita conforme sugestão.
Arquivos referentes ao code coverity mantidos na raiz do repositório por serem tratados na issue #13 e #17.
Pasta doc adicionada, arquivo de texto adicionado somente pelo fato de que o github não armazena pastas vazias. 
**Problema :** Agora o build da branch iss14 falha no Travis. O serviço não encontra o descritor de implantação antes localizado na pasta core. Aguardo sugestão para correção do problema.

**Comment by calebepb** [comment]
A partir da linha 14 do _build.sh_, reescreva algo parecido com:

```shell
ant
exit $?
```

**Comment by jonatasmaxi** [comment]
Build.sh corrigido.
Travis-CI está construindo a build corretamente agora.
Posso criar o pull request para dev ?

**Comment by calebepb** [comment]
No novo _build.sh_, as linhas 17-39 não devem existir: o comando `exit` termina o script.

**Comment by jonatasmaxi** [comment]
Corrigido

**Comment by calebepb** [comment]
Não acho que o diretório `doc` tenha que ter um arquivo desnecessário. Apague aquele reagem e coloque um arquivo de projeto do StarUML (http://staruml.io) que será utilizado para modelagem UML.

**Comment by jonatasmaxi** [comment]
Ok, arquivo do StarUML adicionado, aguardando autorização para pull request.

**Comment by calebepb** [comment]
Aguardando pull-request...
