### ISSUE TITLE
Configurar o Code Coverity corretamente

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#17]
É necessário configurar o relatório de Code Coverity para o Codacy. A variável de ambiente necessária para o push do relatório já está pronta no Travis-CI. Precisa apenas configurar o build para capturar o resultado:

- https://github.com/codacy/codacy-coverage-reporter#setup

**ATENÇÃO**
**Não publicar o valor da chave do Codacy (CODACY_PROJECT_TOKEN), pois ela é _sigilosa!!!_**

**Comment by jonatasmaxi** [comment]
Obtendo erro **com.codacy could not retrieve the current commit build**
PS: Obtendo erro ao tentar configurar a coverage nesse repositório, testes realizado a partir do repositório forkado.

**Comment by calebepb** [comment]
Então, minha sugestão é *não trabalhar com fork* (déjà vu #75 ?!?!).

**Comment by jonatasmaxi** [comment]
Trabalhei com fork porque como disse, estou obtendo erro ao tentar configurar a coverage nesse repositório. Ao clicar na página setup coverage para obter o token ele me mostra uma página de erro.

**Comment by jonatasmaxi** [comment]
![image](https://cloud.githubusercontent.com/assets/11192676/15949848/d9e0c3ea-2e80-11e6-9357-ce7601d6ed99.png)

**Comment by calebepb** [comment]
Então, a idea de se trabalhar com uma branch neste repositório é para eu acompanho a evolução do que esta sendo feito. É esse o processo e deve ser seguido assim! :)
A variável `CODACY_PROJECT_TOKEN` já está publicado no Travis-CI e já pode ser usada - **muito cuidado ao fazer uso dela**. Minha _forte_ recomendação é **não** executar o `export CODACY_PROJECT_TOKEN=%Project_Token%`, pois isso já foi feito!
O setup do codacy para este repositório já foi feito - se não, você não veria [este relatório](https://www.codacy.com/app/calebepb/substituicao/dashboard). Além disso, faz sentido apenas o "dono do repositório" ter acesso a configuração do token.
Assim, estou aguardando a branch com o script de coleta e publicação conforme descrito em https://github.com/codacy/codacy-coverage-reporter#setup

**Comment by calebepb** [comment]
1. Desligar a propriedade de `built-clean.properties`.
2. Criar um arquivo geral xml (e.g. `substituiçao.xml`) que chama/importa (?) o `build.xml` criado pelo netbeans - o target padrão é `default`
3. criar um outro xml (eg. `coverage.xml`) com as configuração de execução (não precisa compilar) do JaCoCo (ver http://sonar-jenkins.blogspot.com.br/2012/12/jacoco-code-coverage-with-ant-sonar.html)
4. colocar no script `build.sh` a execução do build geral (algo como `ant -buildfile substituicao.xml`)
5. colocar no script `build.sh` o envio do report para o Codacy

**Comment by calebepb** [comment]
*Acho* que não precisa desligar a propriedade do passo 1. :)

**Comment by jonatasmaxi** [comment]
Aguardando sincronização do codacy.

**Comment by calebepb** [comment]
Feito: https://www.codacy.com/app/calebepb/substituicao/dashboard?bid=3351618

**Comment by jonatasmaxi** [comment]
Encontrado um melhor exemplo do xml para configuração do coverage. 
http://eclemma.org/jacoco/trunk/doc/examples/build/build.xml

**Comment by jonatasmaxi** [comment]
Professor, o arquivo jacoco.exec não está sendo gerado. Estudando o XML postado no link acima http://eclemma.org/jacoco/trunk/doc/examples/build/build.xml percebi que é preciso "encapsular" as atividades de teste com a tag <jacoco:coverage> que possui um atributo chamado destfile que é justamente o responsável para gerar o arquivo relatório de execução. tentei importar o target do-test-run e colocá-lo entre as tags <jacoco:coverage> porém não obtive sucesso, pois a tag não permite operações de importação dentro dela. 
Tentei sobrescrever o build-impl.xml e ao fazer isso descobri o seguinte:
Não é possível sobrescrever o arquivo gerado pelo netbeans (o que fica dentro da nbproject nomeado de build-impl.xml . O _override_ de uma seção desse documento XML acontece no build.xml. O que impede que o trecho sobrescrito seja alterado indesejavelmente pela execução do Netbeans. O intuito era sobrescrever a seção -do-test-run para encapsular as atividades de teste com a tag exigida. Porém estou obtendo o erro **failed to create task or type target**  já tentei fazer a importação do taskdef do ant e nada feito também. 
Já havia alterado o build.sh para que chamasse o substiuição.xml para realizar as tarefas pertinentes ao jacoco. Retirei a importação do build.xml do substituicao.xml como sugerido no passo 1 pois isso fazia com que a build fosse feita duas vezes, o comando ant do build.sh já executa o build.xml
Acabei por definir todas as propriedades na mão.
Trocando em miúdos, fiz até o passo 4. Porém não há como saber se está correto até conseguir arrumar o problema de geração do jacoco.exec. 
Vou subir as modificações do build.xml inclusive com a importação do taskdef do ant, o que deve fazer a build parar de funcionar por total na branch issue-17, para reversão basta remover a tentativa de sobrescrita do trecho do código no documento.
Vou continuar tentando por aqui, se tiver alguma sugestão...

**Comment by jonatasmaxi** [comment]
Ok, consegui sobrescrever o -do-test-run para adequá-lo ao formato dos dois links de exemplo que temos. O arquivo jacoco.exec é gerado porém somente um teste é executado. Segundo o log do travis-ci uma exceção do tipo **AssertionFailedError** faz com que os testes crashem. Peço que por favor verifique isso pra mim, vou prosseguir para a geração do report afinal tenho o arquivo jacoco-exec agora.

**Comment by jonatasmaxi** [comment]
Consegui fazer com que o report fosse gerado. Porém não obtive sucesso em retirar o override do do-compile-test do build.xml. Tudo funcionando. Porém os testes estão falhando. Estou tentando ajeitar o build.sh para enviar o relatório mesmo com falha ao codacy só a efeito de testes. Feito isso, acredito que esteja encerrado,

**Comment by jonatasmaxi** [comment]
Obtendo erro na hora da execução do comando referente ao codacy-coverage-reporter. Alguma dependência a mais é necessária além dos comandos do setup? https://github.com/codacy/codacy-coverage-reporter#setup

**Comment by jonatasmaxi** [comment]
Retificação:
Ainda obtendo erro no build.sh me parece que o travis não consegue executar a linha codacy-coverage-reporter
O problema com os testes está ocorrendo na definição do diretório. Aparentemente alguma task do ant não está sendo construída com sucesso.
Favor olhar o email...

**Comment by calebepb** [comment]
Vou olhar, mas... não tem nada nesse e-mail que seja técnico para ser registrado aqui, além do que já foi registrado?

**Comment by calebepb** [comment]
Fiz algumas alterações na branch - tome cuidado ao fazer pull (o melhor é remover a branch local e fazer pull novamente).
Porém, não entendi porque o coverage no site do codacy está mostrando apenas para as classes de testes - esta não "usam" as demais classes?

**Comment by jonatasmaxi** [comment]
Nesse caso o report foi configurado apenas para os testes rodados, desconheço a possibilidade de geração de um report para execução das classes, mas posso verificar.

**Comment by calebepb** [comment]
Ah, esse problema foi resolvido, veja o commit f7b4021. Era problema de referência aos arquivos .class (propriedade `build.classes.dir`)
