### ISSUE TITLE
Classes entidade e modelo possuem propósitos equivalentes

### ISSUE THREAD

**Issue by william-wc** [Prof-Calebe/substituicao#24]
As classes modelo (/modelo) e entidade (/dominio) possuem (quase) todos os mesmos atributos.
E sempre que uma classe modelo é utilizada, é feita como uma cópia da sua equivalência em entidade.

Em **ProfessorModel**, falta o atributo **username**

**Comment by calebepb** [comment]
Igual ao issue #12 - trabalhar naquele item e, se for o caso, justificar a re-abertura deste issue.
