### ISSUE TITLE
ProfessorService excesso de encadeamento de IFs além de uma checagem extra de um booleano 

### ISSUE THREAD

**Issue by william-wc** [Prof-Calebe/substituicao#25]
`for(Professor professor : todosProfessores){
    
    if(!professor.equals(professorAusente)){
        //profsMenosAusente.add(professor);
        
        if(professor.EhCompativelCom(aulasPerdidas)){
            
            Boolean compatível = true;
            
            for(Ausencia ausenciaPreExistente : todasAsAusencias)
            {
                if(ausenciaPreExistente.getProfessorSubstituto() != null)
                {
                    if(ausenciaPreExistente.getProfessorSubstituto().getNome().equals(professor.getNome()))
                    {
                        if(ausenciaPreExistente.getPeriodo().overlaps(ausência.getPeriodo()))
                            compatível = false;
                    }
                }
            }
            
            if(compatível)
            {
                ProfessorModel model = new ProfessorModel();

                model.id = professor.getId();
                model.Nome = professor.getNome();

                profsPossiveis.add(model);
            }
        }
    }   
}`

**Comment by calebepb** [comment]
Neste caso, não está claro qual o comportamento desse trecho de código. 
Assim, se houver uma refatoração, criar casos de testes **antes** de modificar para garantir que o comportamento seja o mesmo.

**Comment by william-wc** [comment]
```
for(Professor professor : todosProfessores){
    
    if(!professor.equals(professorAusente)){
        //profsMenosAusente.add(professor);
        
        if(professor.EhCompativelCom(aulasPerdidas)){
            
            Boolean compatível = true;
            
            for(Ausencia ausenciaPreExistente : todasAsAusencias)
            {
                if(ausenciaPreExistente.getProfessorSubstituto() != null)
                {
                    if(ausenciaPreExistente.getProfessorSubstituto().getNome().equals(professor.getNome()))
                    {
                        if(ausenciaPreExistente.getPeriodo().overlaps(ausência.getPeriodo()))
                            compatível = false;
                    }
                }
            }
            
            if(compatível)
            {
                ProfessorModel model = new ProfessorModel();

                model.id = professor.getId();
                model.Nome = professor.getNome();

                profsPossiveis.add(model);
            }
        }
    }   
}
```

É possível reduzir para

```
for(Professor professor : todosProfessores) {
    if(professor.equals.(professorAusente) || professor.EhCompativelCom(aulasPerdidas)) {
        continue;
    }

    Boolean compatível = true;

    for(Ausencia ausenciaPreExistente : todasAsAusencias) {
        if(ausenciaPreExistente.getProfessorSubstituto != null 
            && ausenciaPreExistente.getProfessorSubstituto().getNome().equals(professor.getNome()
            && ausenciaPreExistente.getPeriodo().overlaps(ausenciaPreExistente.getPeriodo())) {
            compatível = false;
            break;
        }
    }

    if(compatível) {
        ProfessorModel model = new ProfessorModel();

        model.id = professor.getId();
        model.Nome = professor.getNome();

        profsPossiveis.add(model);
    }
}
```

Outras observações: 
`if(ausenciaPreExistente.getProfessorSubstituto().getNome().equals(professor.getNome()))`
ao invés de comparar nomes, por que não comparar os próprios objetos (Professor)?

Esta checagem pode não ser necessária pois em _Ausencia_, **professorSubstituto** está encapsulado de tal jeito que não é possível adicionar o mesmo tanto como professor da ausência quanto como substituto dela
```
public void setProfessorSubstituto(Professor professorSubstituto) {
    if (professorSubstituto == this.professor){
        throw new IllegalStateException("O professor substituto não deve ser o mesmo que o professor se ausentando.");
    }
    
    this.professorSubstituto = professorSubstituto;
    this.definirComoAlocado();
}
```

```
public void indicarSubstituto(Professor professor) {
        
    if (professor == this.professor){
        throw new IllegalStateException("O professor substituto não deve ser o mesmo que o professor se ausentando.");
    }
    //this.indicacaoSubstituto = professor;
    
    this.indicacoesSubstituto.add(professor);
}
```

**Comment by calebepb** [comment]
Acho que vale a pena refatorar esse código, tentando melhorar a coesão desse método!
Faça as melhorias necessárias!

**Comment by william-wc** [comment]
`if(ausenciaPreExistente.getProfessorSubstituto().getNome().equals(professor.getNome()))`
É necessário, pois checa se o horário daquela ausência (percorrida) conflita com o horário da ausência checada, para aquele professor.

**Comment by calebepb** [comment]
Fixed.
