### ISSUE TITLE
NotificacaoService.java encadeia IFs percorrendo um enum

### ISSUE THREAD

**Issue by william-wc** [Prof-Calebe/substituicao#28]
private String determinarEstado(EstadoAusencia estado){
        if(estado == EstadoAusencia.Ausencia_Cancelada)
            return "Ausência cancelada";
        else if(estado == EstadoAusencia.Alocacao_Efetuada)
            return "Alocação efetuada";
        else if(estado == EstadoAusencia.Alocacao_Pendente)
            return "Alocação pendente";
        else if(estado == EstadoAusencia.Alocacao_Confirmada)
            return "Alocação confirmada";
        else{
            return "Aulas canceladas";
        }
    }

Possível mudar por switch-case

**Comment by calebepb** [comment]
E, porque não algo como:

```
private String determinarEstado(EstadoAusencia estado){
  return estado.toString():
} 
```

?
Aliás, qual o motivo de se retornar String?

**Comment by calebepb** [comment]
Fixed.
