### ISSUE TITLE
Especificação dos Casos de Uso: utilização de Botões

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#3]
É importante deixar as especificações sem detalhes de layout ou projeto de UI.

**Comment by BrunaFerreira** [comment]
# CSU01 - Notificar Ausência

<table>
<tbody>
  <tr>
    <td><b>Identificador</b></td>
    <td>CSU01</td>
  </tr>
    <td><b>Nome</b></td>
    <td>Notificar Ausência</td>
  </tr>
  <tr>
    <td><b>Atores</b></td>
    <td>Funcionário</td>
  </tr>
  <tr>
    <td><b>Sumário</b></td>
    <td>Um funcionário notifica que um professor se ausentará. O ator também pode ser o próprio professor, <ins>ou seja o próprio professor pode notificar sua ausência.</ins></td>
  </tr>
  <tr>
     <td><b>Complexidade</b></td>
     <td>Médio </td>
  </tr>
   <tr>
     <td><b>Regras de Negócio</b></td>
     <td>N/D </td>
  </tr>
  <tr>
     <td><b>Pré-condições</b></td>
     <td>O ator deve estar autenticado no sistema. </td>
  </tr>
  <tr>
      <td><b>Pós-condição</b></td>
      <td>Uma nova notificação de ausência é cadastrada no sistema.</td>
  </tr>
  <tr>
      <td><b>Pontos de Inclusão</b></td>
      <td>N/D</td>
  </tr> 
  <tr>
    <td><b>Pontos de Extensão</b></td>
    <td>N/D</td>
  </tr> 
  </tbody>
</table>
<br>
<table>
   <caption><b>Fluxo Principal</b></caption>
 <tbody>
  <tr>
     <td><b>Usuário</b></td>
     <td><b>Sistema</b></td>
  </tr>
  <tr>
     <td>1. Ator <del>clica no botão "Nova Notificação de Ausência"..</del> inicia o registro da notificação de ausência.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>2. Sistema exibe formulário de nova notificação de ausência.</td>
  </tr>
  <tr>
     <td>3. Ator seleciona o professor ausente.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>4. Sistema popula grade do professor.</td>
  </tr>
  <tr>
     <td>5. Ator informa período(s) de ausência, e o motivo.</td>
     <td></td>
  </tr>
  <tr>
     <td>6. Ator <del>clica em "confirmar".</del> confirma envio de seu formulário.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>7. Sistema grava nova notificação de ausência com status "Aguardando Alocação"</td>
    
  </tr>
  </tbody>
</table>
<br>

## Fluxo de Exceção  - Passo 6
<table>
<tbody>
<tr>Condição: Ator não informa um motivo.</p></tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td></td>
    <td>6.1 Sistema informa ao ator que o campo é obrigatório.</td>
  </tr>
  <tr>
    <td></td>
    <td>6.2 Retorna ao passo 5.</td>
  </tr>
 </tbody>
</table>
<br>
![](https://raw.githubusercontent.com/BrunaFerreira/ImagesSubstituicao/master/CS01.png)

**Comment by BrunaFerreira** [comment]
# CSU01 - Notificar Ausência

<table>
<tbody>
  <tr>
    <td><b>Identificador</b></td>
    <td>CSU01</td>
  </tr>
    <td><b>Nome</b></td>
    <td>Notificar Ausência</td>
  </tr>
  <tr>
    <td><b>Atores</b></td>
    <td>Funcionário</td>
  </tr>
  <tr>
    <td><b>Sumário</b></td>
    <td>Um funcionário notifica que um professor se ausentará. O ator também pode ser o próprio professor, <ins>ou seja o próprio professor pode notificar sua ausência.</ins></td>
  </tr>
  <tr>
     <td><b>Complexidade</b></td>
     <td>Médio </td>
  </tr>
   <tr>
     <td><b>Regras de Negócio</b></td>
     <td>N/D </td>
  </tr>
  <tr>
     <td><b>Pré-condições</b></td>
     <td>O ator deve estar autenticado no sistema. </td>
  </tr>
  <tr>
      <td><b>Pós-condição</b></td>
      <td>Uma nova notificação de ausência é cadastrada no sistema.</td>
  </tr>
  <tr>
      <td><b>Pontos de Inclusão</b></td>
      <td>N/D</td>
  </tr> 
  <tr>
    <td><b>Pontos de Extensão</b></td>
    <td>N/D</td>
  </tr> 
  </tbody>
</table>
<br>
<table>
   <caption><b>Fluxo Principal</b></caption>
 <tbody>
  <tr>
     <td><b>Usuário</b></td>
     <td><b>Sistema</b></td>
  </tr>
  <tr>
     <td>1. Ator <del>clica no botão "Nova Notificação de Ausência"..</del> inicia o registro da notificação de ausência.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>2. Sistema exibe formulário de nova notificação de ausência.</td>
  </tr>
  <tr>
     <td>3. Ator seleciona o professor ausente.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>4. Sistema popula grade do professor.</td>
  </tr>
  <tr>
     <td>5. Ator informa período(s) de ausência, e o motivo.</td>
     <td></td>
  </tr>
  <tr>
     <td>6. Ator <del>clica em "confirmar".</del> confirma envio de seu formulário.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>7. Sistema grava nova notificação de ausência com status "Aguardando Alocação"</td>
    
  </tr>
  </tbody>
</table>
<br>

## Fluxo de Exceção  - Passo 6
<table>
<tbody>
<tr>Condição: Ator não informa um motivo.</p></tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td></td>
    <td>6.1 Sistema informa ao ator que o campo é obrigatório.</td>
  </tr>
  <tr>
    <td></td>
    <td>6.2 Retorna ao passo 5.</td>
  </tr>
 </tbody>
</table>
<br>
![](https://raw.githubusercontent.com/BrunaFerreira/ImagesSubstituicao/master/CS01.png)

**Comment by BrunaFerreira** [comment]
# CSU02 - Efetuar Alocação

<table>
<tbody>
  <tr>
    <td><b>Identificador</b></td>
    <td>CSU02</td>
  </tr>
    <td><b>Nome</b></td>
    <td>Efetuar Alocação</td>
  </tr>
  <tr>
    <td><b>Atores</b></td>
    <td>Administrador</td>
  </tr>
  <tr>
    <td><b>Sumário</b></td>
    <td>Um Administrador visualiza uma Notificação de Ausência e escala um Professor para cobri-la.</td>
  </tr>
  <tr>
     <td><b>Complexidade</b></td>
     <td>Médio </td>
  </tr>
   <tr>
     <td><b>Regras de Negócio</b></td>
     <td>N/D </td>
  </tr>
  <tr>
     <td><b>Pré-condições</b></td>
     <td>O ator deve estar autenticado no sistema e deve haver pelo menos uma alocação pendente. </td>
  </tr>
  <tr>
      <td><b>Pós-condição</b></td>
      <td>Sistema atualiza alocação para "Alocação Confirmada".</td>
  </tr>
  <tr>
      <td><b>Pontos de Inclusão</b></td>
      <td>N/D</td>
  </tr> 
  <tr>
    <td><b>Pontos de Extensão</b></td>
    <td>N/D</td>
  </tr> 
  </tbody>
</table>
<br>
###  Fluxo Principal
<table>
 <tbody>
  <tr>
     <td><b>Usuário</b></td>
     <td><b>Sistema</b></td>
  </tr>
  <tr>
     <td>1. Ator <del>clica no botão "Notificações Pendentes".</del> consulta notificaçõesde alocação  pendentes.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>2. Sistema exibe listagem de notificações pendentes.</td>
  </tr>
  <tr>
     <td>3. Ator seleciona uma das notificações da lista.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>4. Sistema exibe formulário de ausência. <del>, em modo read-only</del>.</td>
  </tr>
  <tr>
     <td>5. Ator <del>clica no botão "Alocar Substituto".</del> solicita alocar professor substituto.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>6. Sistema exibe lista de professores com horários vagos na grade compatíveis com a ausência.</td>
  </tr>
  <tr>
     <td>7. Ator seleciona um dos professores listados</td>
     <td></td>    
  </tr>

  <tr>
     <td>8. Ator <del>clica no botão "Confirmar".</del> confirma alocação. </td>
     <td></td>  
  </tr>

  <tr>
     <td></td>
     <td>9. Sistema grava as alterações e atualiza a notificação de ausência para "Alocação Confirmada".</td>
    </tr>
  </tbody>
</table>
<br>
### Fluxo de Exceção  - Passo 5
<table>
<tbody>
<tr>Condição: Não existem professores compatíveis.</p></tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td></td>
    <td>6.1 Sistema informa ao ator que não existem professores com grade compatível.</td>
  </tr>
  <tr>
    <td></td>
    <td>6.2 Retorna ao passo 4.</td>
  </tr>
 </tbody>
</table>
<br>
![](https://raw.githubusercontent.com/BrunaFerreira/ImagesSubstituicao/master/CS02.png)

**Comment by BrunaFerreira** [comment]
# CSU09 - Criação de Usuários

<table>
<tbody>
  <tr>
    <td><b>Identificador</b></td>
    <td>CSU09</td>
  </tr>
    <td><b>Nome</b></td>
    <td>Criação de Usuários</td>
  </tr>
  <tr>
    <td><b>Atores</b></td>
    <td>Administrador</td>
  </tr>
  <tr>
    <td><b>Sumário</b></td>
    <td>Cadastro de novos usuários no Sistema.</td>
  </tr>
  <tr>
     <td><b>Complexidade</b></td>
     <td>Baixo </td>
  </tr>
   <tr>
     <td><b>Regras de Negócio</b></td>
     <td> RN09 </td>
  </tr>
  <tr>
     <td><b>Pré-condições</b></td>
     <td>Usuário não pode estar cadastrado no sistema </td>
  </tr>
  <tr>
      <td><b>Pós-condição</b></td>
      <td>Usuário possui cadastro no sistema.</td>
  </tr>
  <tr>
      <td><b>Pontos de Inclusão</b></td>
      <td>N/D</td>
  </tr> 
  <tr>
    <td><b>Pontos de Extensão</b></td>
    <td>N/D</td>
  </tr> 
  </tbody>
</table>
<br>
###  Fluxo Principal
<table>
 <tbody>
  <tr>
     <td><b>Usuário</b></td>
     <td><b>Sistema</b></td>
  </tr>
  <tr>
     <td>1. <del>Usuário clica no botão “criar novo usuário”.</del>Ator inicia cadastro de novo usuário.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>2. Sistema exibe formulário de preenchimento de dados</td>
  </tr>
  <tr>
     <td>3. <del>Usuário preenche o formulário e clica e avançar.</del> Ator preenche formulário e envia dados. </td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>4. Sistema verifica os dados e exibe a mensagem  "Usuário cadastrado com sucesso”</td>
  </tr>
  </tbody>
</table>
<br>
### Fluxo de Exceção  - Passo 3
<table>
<tbody>
<tr><del>Condição: Usuário seleciona o tipo de relatório errado.</del><br>Condição: Ator seleciona o tipo de usuário errado.</p></tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td></td>
    <td>4.1 Sistema verifica os dados e identifica que esse usuário já foi cadastrado exibindo na tela que o usuário já existe.</td>
  </tr>
  <tr>
    <td></td>
    <td>5.1 Sistema volta para o passo 2</td>
  </tr>
 </tbody>
</table>
<br>
### Fluxo de Exceção  - Passo 5
<table>
<tbody>
<tr><td><del>Condição: Usuário cancela o cadastramento de usuário..</del></p><td></tr>
<tr><td>Condição: Cancelamento de cadastro.</p><td></tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td>3.2 Ator cancela o cadastramento do usuário.</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td>4.2 Sistema volta para o passo 1.</td>
  </tr>
 </tbody>
</table>
<br>
![](https://raw.githubusercontent.com/BrunaFerreira/ImagesSubstituicao/master/CS09.png)

**Comment by BrunaFerreira** [comment]
#CSU10 - Edição de Usuário

<table>
<tbody>
  <tr>
    <td><b>Identificador</b></td>
    <td>CSU10 </td>
  </tr>
    <td><b>Nome</b></td>
    <td>Edição de Usuário</td>
  </tr>
  <tr>
    <td><b>Atores</b></td>
    <td>Administrador</td>
  </tr>
  <tr>
    <td><b>Sumário</b></td>
    <td>Alteração no cadastro de usuário de sistemas.</td>
  </tr>
  <tr>
     <td><b>Complexidade</b></td>
     <td>Médio </td>
  </tr>
   <tr>
     <td><b>Regras de Negócio</b></td>
     <td> RN03, RN07, RN09 </td>
  </tr>
  <tr>
     <td><b>Pré-condições</b></td>
     <td>Usuário deve estar cadastrado no sistema.</td>
  </tr>
  <tr>
      <td><b>Pós-condição</b></td>
      <td>Usuário teve suas informações editadas</td>
  </tr>
  <tr>
      <td><b>Pontos de Inclusão</b></td>
      <td>N/D</td>
  </tr> 
  <tr>
    <td><b>Pontos de Extensão</b></td>
    <td>N/D</td>
  </tr> 
  </tbody>
</table>
<br>
###  Fluxo Principal
<table>
 <tbody>
  <tr>
     <td><b>Usuário</b></td>
     <td><b>Sistema</b></td>
  </tr>
  <tr>
     <td>1. Usuário clica no botão “Editar Usuário”.</td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>2. Sistema exibe todos os usuários.</td>
  </tr>
  <tr>
     <td>3. Usuário seleciona o usuário a ser editado. </td>
     <td></td>
  </tr>
  <tr>
     <td></td>
     <td>4. Sistema exibe os dados do usuário.</td>
  </tr>
  <tr>
     <td></td>
     <td>5. Usuário altera os dados desejados.</td>
  </tr>
  <tr>
     <td></td>
     <td>6. Sistema solicita a confirmação da alteração do usuário.</td>
  </tr>
  <tr>
     <td></td>
     <td>7. Usuário confirma alteração.</td>
  </tr>
  <tr>
     <td></td>
     <td>8. Sistema salva as novas informações e atualiza base de dados.</td>
  </tr>
  </tbody>
</table>
<br>
### Fluxo de Exceção  - Passo 7
<table>
<tbody>
<tr>Condição: Usuário cancela alteração de usuário.</tr>
  <tr>
    <td><b>Usuário</b></td>
    <td><b>Sistema</b></td>
  </tr>
  <tr>
    <td></td>
    <td>7.1 Usuário cancela o preenchimento dos dados.</td>
  </tr>
  <tr>
    <td></td>
    <td>8.1 Sistema volta para o passo 1.</td>
  </tr>
 </tbody>
</table>
<br>
<br>
![](https://raw.githubusercontent.com/BrunaFerreira/ImagesSubstituicao/master/CS10.png)

**Comment by calebepb** [comment]
Veja se a atribuição desta atividade deve ser feita para @BrunaFerreira ou @BrunaFerreira7 .

**Comment by calebepb** [comment]
Publicar as sugestões de melhorias das especificações nas issues específicas:

- CSU01: #35 
- CSU02: #36 
- CSU09: #39 
- CSU10: #43

**Comment by BrunaFerreira** [comment]
Continuo no @BrunaFerreira por já estar atribuída a issue. Quanto aos casos de uso incluo como comentário, ou devo alterar a wiki onde os mesmos estão?

**Comment by calebepb** [comment]
Para colocar a @BrunaFerreira como participante, preciso remover a @BrunaFerreira7 da equipe e adicionar a outra conta - se não, a outra conta não conseguirá alterar a wiki.
Quanto as sugestão de mudanças, precisa-se colocar os comentários nas respectivas issues, pois não estão no lugar correto, e depois vou validá-las - está muito suja visualmente esta issue com tanto texto, o que dificulta um trabalho rápido.

**Comment by calebepb** [comment]
Eu já não sei qual a conta que deve ser usada mais... :(

**Comment by BrunaFerreira7** [comment]
Tentei fazer commit das alterações pelos dois usuários, mas nenhum está autorizado. :(

**Comment by calebepb** [comment]
Adicionada @BrunaFerreira7 novamente, cancelado o convite de @BrunaFerreira .

**Comment by BrunaFerreira7** [comment]
@calebepb Wiki  alterada, com soluções propostas.

**Comment by calebepb** [comment]
Não era para alterar a wiki antes de validar os comentários das respectivas wikis, como disse alguns comentários atrás.

**Comment by calebepb** [comment]
Wiki revertida para última versão estável.

**Comment by BrunaFerreira** [comment]
Aguardando validações.

**Comment by BrunaFerreira7** [comment]
@calebepb Aguardando validação das issues.

**Comment by calebepb** [comment]
Essa tarefa se tornou um pouco "épica". Vou fechá-la para abrir tarefas mais específicas conforme problemas forem encontrados - precisa de uma inspeção mais detalhada!
