### ISSUE TITLE
Problema no caminho das imagens na Apresentacao

### ISSUE THREAD

**Issue by lucastedeschi** [Prof-Calebe/substituicao#32]
Cada arquivo da Apresentacao utiliza imagens que não podem ser encontradas devido ao fato de estarem com o caminho apontando para uma máquina local ("_C:/Users/Thiago/Documents/NetBeansProjects/ProSub/..._").

**Comment by calebepb** [comment]
Corrigir para todas as imagens da camada de `apresentacao`.

**Comment by calebepb** [comment]
pull-request #89 merged.
