### ISSUE TITLE
Adicionar um exemplo de uso do NoSY no README.MD

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#34]
Como não utilizamos a branch `master` como base para o desenvolvimento (mas a `dev`), e em função do Git Branch Model (mas não usamos `--no-ff`), acredito que seja interessante deixar um exemplo de como usar esses dois modelos na seção [Git & Branches](https://github.com/Prof-Calebe/substituicao#git--branches) do README.MD

**Comment by calebepb** [comment]
Algo assim poderia ser colocado como exemplo:

----
* Faça a sua `branch` a partir da `dev`, substituindo **##** pelo número da issue que foi documentada.
```bash
$ git checkout -b [issue-##] dev
```

* A partir de então, faça as alterações e sempre realize `commit` para marcar a evolução da correção.
```bash
$ git add # arquivos
$ git commit # com os seus commits
```

* Uma vez finalizada as alterações, sincronize sua `branch` com a `dev`.
```bash
$ git checkout dev
$ git pull
$ git checkout [issue-##]
$ git rebase origin/dev
```

* Se não tiver conflitos, envie suas alterações para o repositório.
```bash
$ git push origin HEAD
```

* Aguarde o build e demais hooks avaliarem a `branch`. Faça um pull-request da `branch-##` para a `dev` e aguarde os comentários da revisão.

* Caso precise alterar sua `branch` em função da falha do build, dos hooks, ou dos comentários de revisão, faça-os normalmente na sua branch `issue-##`, sincronizando-a novamente ao final e reenviando para o repositório. Aguarde os resultados do passo anterior e, se for o caso, repita todo este processo.
```bash
$ git checkout [issue-##]
$ git add # arquivos
$ git commit # com os seus commits
$ git rebase origin/dev
$ git push --force origin HEAD
```
----

Alguém pode avaliar se isso funciona mesmo e comentar aqui?

**Comment by jonatasmaxi** [comment]
Professor, criei a branch issue17 no fork do meu repositório usando os comandos acima, está tudo OK. Exceto pelo primeiro comando que tive de especificar o caminho completo para o branch dev. Assim, o primeiro comando ficaria  dessa maneira:
git checkout -b [issue-##] remotes/origin/dev  
Tirando isso o resto tudo OK.

**Comment by jonatasmaxi** [comment]
Apesar da issue não ser de minha responsabilidade, criei uma nova branch nomeada de issue34 e adicionei o exemplo acima, alterado de acordo com os testes que realizei. Aguardando autorização para pull request.

**Comment by calebepb** [comment]
Ah, não esquece que a `branch` deve ter o formato `issue-##`, com o hífen.

**Comment by calebepb** [comment]
Aguardando pull-request...

**Comment by jonatasmaxi** [comment]
Pull request aberto, devo dar assign dessa tarefa?
