### ISSUE TITLE
Configurar o codady para usar 120 caracteres por linha de code convention

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#49]
O codacy define um padrão denominado _Checks for long lines_, que é uma opção do [Checklist ](http://checkstyle.sourceforge.net/checks.html) chamado [LineLength](http://checkstyle.sourceforge.net/config_sizes.html#LineLength).

**Comment by mimassotti** [comment]
# Passo a passo para alterar o numero de caracteres por linha:

Entre no codacy e selecione o seu repositório.
![Image of Yaktocat](http://i.imgur.com/ei9Gqwm.png)


Entre no editor de code pattens 
![Image of Yaktocat](http://i.imgur.com/V6WFzYU.png)

Procure por excessive line length
![Image of Yaktocat](http://i.imgur.com/4F4GXsU.png)
![Image of Yaktocat](http://i.imgur.com/QcaG9VL.png)

Mude para o numero de linhas desejados (180)
![Image of Yaktocat](http://i.imgur.com/caVdT2g.png)

Reavalie o codigo
![Image of Yaktocat](http://i.imgur.com/hfiAhAv.png)

**Comment by calebepb** [comment]
Não é a opção _'excessive line length'_, pois ela funciona apenas para Javascript. Deve ser a opção _'Checks for long lines'_ que funciona para Java.
