### ISSUE TITLE
Verificar divergências: CSU01 - Notificar Ausência

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#63]
Comparar diferenças entre documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by freddysaar** [comment]
#Diferenças:
Pedro (prgoes-mack) | Calebe (Prof-Calebe
------------ | -------------
Regras de Negócio: TODO | Regras de Negócio:
5. Ator informa período(s) de ausência, o motivo e professores indicados para substituição. | 5. Ator informa período(s) de ausência, e o motivo.

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by calebepb** [comment]
Corrigir o CSU01 conforme sugestões do Pedro.

**Comment by freddysaar** [comment]
Corrigido conforme sugestões.

**Comment by calebepb** [comment]
A wiki foi corrompida: issue reaberta. Antes de fechar, aguardar correções da @BrunaFerreira7

**Comment by calebepb** [comment]
Feito
