### ISSUE TITLE
Verificar divergências: CSU02 - Efetuar Alocação

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#64]
Comparar diferenças entre documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by freddysaar** [comment]
Pedro (prgoes-mack) |  Calebe (Prof-Calebe)
------------ | -------------
**Regras de Negócio:** TODO | **Regras de Negócio:**

**Comment by calebepb** [comment]
Alterar conforme Pedro.

**Comment by calebepb** [comment]
Feito.
