### ISSUE TITLE
Verificar divergências: CSU03 - Efetuar Realocação

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#65]
Comparar diferenças entre documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by freddysaar** [comment]
### Diferenças:

Pedro (prgoes-mack) |  Calebe (Prof-Calebe)
------------ | -------------
Regras de Negócio: TODO | Regras de Negócio:

**Comment by freddysaar** [comment]
Wiki atualizado.

**Comment by calebepb** [comment]
Wiki corrompida: reabrindo issue.

**Comment by calebepb** [comment]
Antes de fechar esta issue, aguardar minha sugestão em relação ao que deve ser feito como alteração, para cada Caso de Uso.
Neste caso, alterar conforme sugestão do Pedro.

**Comment by freddysaar** [comment]
Ok. Alterado conforme sugestão do Pedro.
