### ISSUE TITLE
Verificar divergências: CSU04 - Eleger para Alocação

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#66]
Comparar diferenças entre documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by freddysaar** [comment]
### Diferenças:

Pedro (prgoes-mack) |  Calebe (Prof-Calebe) | 
------------ | -------------
Regras de Negócio: TODO | Regras de Negócio:
**Atores:** Professor | **Atores:** Professor e Administrador

**Comment by calebepb** [comment]
Manter os atores Professor e Administrador.
