### ISSUE TITLE
Verificar divergências: CSU05 - Rejeitar Alocação

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#67]
Comparar documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by freddysaar** [comment]
Pedro (prgoes-mack) |  Calebe (Prof-Calebe) | 
------------ | -------------
**Atores:** Funcionário | **Atores:** Professor

**Comment by calebepb** [comment]
Acho mais prudente manter o ator Professor, em função do domínio do problema.
