### ISSUE TITLE
Verificar divergências: CSU06 - Cancelar Ausência

### ISSUE THREAD

**Issue by freddysaar** [Prof-Calebe/substituicao#68]
Comparar documentação do projeto atual e do fork do Pedro (prgoes-mack).

**Comment by calebepb** [comment]
Divisão em atividades menores da issue #10.

**Comment by freddysaar** [comment]
Pedro (prgoes-mack) |  Calebe (Prof-Calebe) | 
------------ | -------------
**Sumário:** É possível fazer o cancelamento da ausência do professor pelo Funcionário. | **Sumário:** Cancelamento da ausência do professor.

**Comment by calebepb** [comment]
Ajuste feito.
