### ISSUE TITLE
Especificar CSU00 - Fazer login

### ISSUE THREAD

**Issue by calebepb** [Prof-Calebe/substituicao#72]

**Comment by denisloide** [comment]
# CSU00 - Efetuar Login

<table>
   <tr><td><b>Identificador</b></td><td>CSU00</td></tr>
   <tr><td><b>Nome</b></td><td>Efetuar Login</td></tr>
   <tr><td><b>Atores</b></td><td>Funcionário</td></tr>
   <tr><td><b>Sumário</b></td><td>Um funcionário entra com suas credenciais no sistema, através da tela de login, e ao ser autenticado pelo sistema, pode acessar suas funcionalidades</td></tr>
   <tr><td><b>Complexidade</b></td><td>Médio</td></tr>
   <tr><td><b>Regras de Negócio</b></td>RN03 - Autenticação no Sistema<td></td></tr>
   <tr><td><b>Pré-Condições</b></td><td>O ator deve estar cadastrado no sistema</td></tr>
   <tr><td><b>Pós-Condições</b></td><td>Liberar acesso ao ator para as funcionalidades do sistema</td></tr>
   <tr><td><b>Pontos de Inclusão</b></td><td></td></tr>
   <tr><td><b>Pontos de Extensão</b></td><td></td></tr>
</table>

<table>
   <tr><td colspan="2"><b>Fluxo Principal</b></td></tr>
   <tr><td><b>Usuário</b></td><td><b>Sistema</b></td></tr>
   <tr><td></td><td>1. Sistema exibe um formulário de login.</td></tr>
   <tr><td>2. Ator digita seu nome de usuário no campo "usuário" e sua senha no campo "senha", e clica no botão "entrar".</td><td></td></tr>
   <tr><td></td><td>3. Sistema valida as credencias do usuário.</td></tr>
   <tr><td></td><td>4. Sistema disponibiliza para o usuário o menu com suas funcionalidades.</td>  </tr>
</table>

<table>
   <tr><td colspan="2"><b>Fluxo De Exceção - Passo 3</b></td></tr>
   <tr><td colspan="2">Condição: Credenciais indicadas pelo ator não estão cadastradas no sistema.</td></tr>
   <tr><td><b>Usuário</b></td><td><b>Sistema</b></td></tr>
   <tr><td></td><td>3.1 Sistema informa que o login não foi autorizado.</td></tr>
   <tr><td></td><td>3.2 Retorna ao passo 1.</td></tr>
</table>

**Comment by calebepb** [comment]
- [ ] Atores: Funcionário, Administrador, Professor
- [ ] Sumário: Autenticar qualquer um dos atores, por meio de credenciais, para acesso ao sistema
- [ ] Pós-Condição: Liberar acesso das funcionalidades do sistema conforme perfil do ator
- [ ] Trocar texto da coluna dos Fluxos de Usuário para Ator
- [ ] Passo 1 do FP: Sistema exibe um formulário de login, contendo a identificação do usuário e sua senha.
- [ ] Passo 2 do FP: Ator informa suas credenciais
- [ ] Passo 5 do FP: Sistema permite acesso às funcionalidades do sistema, conforme perfil do Ator autenticado
- [ ] Condição do FE-3: Credenciais indicadas não foram validadas pelo sistema (não diferenciar os diversos tipos de erros - e.g. não cadastrados; inválidos - por questão de segurança)
- [ ] renumerar passos do FE-3, iniciando-se em 1
- [ ] Passo 1 do FE-3: Sistema mostra uma mensagem "Usuário não autenticado no sistema".
- [ ] Passo 2 do FE-3: Retorna ao passo 1 do Fluxo Principal

**Comment by denisloide** [comment]
@calebepb Caso de uso editado, mas surgiu duvida quanto à alteração no passo 5, seria no 5 mesmo ou no 4?

**Comment by calebepb** [comment]
Acho que seria mesmo no passo 4. Pelo visto, você já fez isso neste passo, não é?
Pode criar a página na wiki do CSU00, com indicações das referências na página de [Casos de Uso](https://github.com/Prof-Calebe/substituicao/wiki/Casos-de-Uso).

**Comment by denisloide** [comment]
Fiz.. aparentemente não posso editar a wiki ou criar uma nova página, pode verificar para mim?

**Comment by calebepb** [comment]
Aceite o convite de autoria. Ele havia sido removido.

On Tue, Jun 21, 2016 at 10:43 AM, Denis Rossi Policastro <
notifications@github.com> wrote:

> Fiz.. aparentemente não posso editar a wiki ou criar uma nova página, pode
> verificar para mim?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Prof-Calebe/substituicao/issues/72#issuecomment-227443577>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfU1FydLz4jbfxzNfSgLTZzziWhim4Xks5qN-qVgaJpZM4Iu560>
> .
>



-- 
Calebe de Paula Bianchini
<http://lattes.cnpq.br/4570923990252346>
<http://br.linkedin.com/pub/calebe-de-paula-bianchini/61/7a4/559/>
<https://www.facebook.com/calebe.bianchini>

---------
NOTA DE CONFIDENCIALIDADE / DISCLAIMER

Esta mensagem, incluindo seus anexos, tem caráter confidencial e seu
conteúdo é restrito ao destinatário da mensagem. Caso você tenha recebido
esta mensagem por engano, queira por favor retorná-la ao destinatário e
apagá-la de seus arquivos. Qualquer uso não autorizado, replicação ou
disseminação desta mensagem ou parte dela é expressamente proibido.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorized copying, disclosure or distribution of the material in this
e-mail is strictly forbidden.
---------
*Soli Deo Gloria*

**Comment by denisloide** [comment]
wiki alterada.
